import React, { useState } from 'react';
import { Sparkles, Loader2, Download, AlertCircle } from 'lucide-react';
import { generateSneakerImage } from '../services/geminiService';
import { ImageSize, Product } from '../types';

interface CustomGeneratorProps {
  onAddToCatalog: (product: Product) => void;
}

export const CustomGenerator: React.FC<CustomGeneratorProps> = ({ onAddToCatalog }) => {
  const [prompt, setPrompt] = useState('');
  const [size, setSize] = useState<ImageSize>(ImageSize.OneK);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt) return;
    
    setIsGenerating(true);
    setError(null);
    setGeneratedImage(null);

    try {
      const image = await generateSneakerImage(prompt, size);
      setGeneratedImage(image);
    } catch (err: any) {
      setError(err.message || 'Failed to generate image. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAddToCatalog = () => {
    if (!generatedImage) return;
    
    const newProduct: Product = {
      id: `custom-${Date.now()}`,
      name: `Custom Design: ${prompt.substring(0, 20)}...`,
      brand: 'Kenya-Amazon Custom',
      price: 199.00,
      description: `A unique custom design generated by AI. Prompt: "${prompt}"`,
      image: generatedImage,
      sizes: [7, 8, 9, 10, 11, 12],
      category: 'Custom',
      rating: 5,
      reviews: 0
    };

    onAddToCatalog(newProduct);
    // Visual feedback handled by parent or reset state here if desired
    alert("Design added to catalog!");
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="text-center max-w-2xl mx-auto mb-12">
        <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight sm:text-5xl mb-4">
          Design Your Future
        </h1>
        <p className="text-lg text-gray-500">
          Use our AI-powered studio to create the sneaker of your dreams. Describe it, choose your quality, and generate.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
        {/* Controls */}
        <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-8">
          <div className="space-y-6">
            <div>
              <label htmlFor="prompt" className="block text-sm font-medium text-gray-700 mb-2">
                Describe your sneaker
              </label>
              <textarea
                id="prompt"
                rows={4}
                className="w-full rounded-lg border-gray-300 border p-3 focus:ring-indigo-500 focus:border-indigo-500"
                placeholder="e.g. A futuristic high-top sneaker made of neon green glass and carbon fiber, cyberpunk style..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Image Quality
              </label>
              <div className="grid grid-cols-3 gap-3">
                {[ImageSize.OneK, ImageSize.TwoK, ImageSize.FourK].map((s) => (
                  <button
                    key={s}
                    onClick={() => setSize(s)}
                    className={`py-3 px-4 rounded-lg text-sm font-bold border transition-all ${
                      size === s
                        ? 'bg-indigo-600 border-indigo-600 text-white shadow-md'
                        : 'bg-white border-gray-200 text-gray-700 hover:border-indigo-300'
                    }`}
                  >
                    {s}
                  </button>
                ))}
              </div>
              <p className="mt-2 text-xs text-gray-500">
                Note: 2K and 4K resolutions require a paid API key selection.
              </p>
            </div>

            <button
              onClick={handleGenerate}
              disabled={isGenerating || !prompt}
              className={`w-full py-4 px-6 rounded-xl text-white font-bold text-lg flex items-center justify-center gap-2 transition-all ${
                isGenerating || !prompt
                  ? 'bg-gray-300 cursor-not-allowed'
                  : 'bg-black hover:bg-gray-800 shadow-lg hover:shadow-xl transform hover:-translate-y-1'
              }`}
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Dreaming...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate Design
                </>
              )}
            </button>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
                <p className="text-sm text-red-700">{error}</p>
              </div>
            )}
            
            <div className="bg-blue-50 border border-blue-100 rounded-lg p-4">
              <p className="text-xs text-blue-700">
                 This feature uses <strong>gemini-3-pro-image-preview</strong>. You may be prompted to select a Google Cloud Project API Key for billing if selecting high resolutions.
              </p>
            </div>
          </div>
        </div>

        {/* Preview */}
        <div className="relative aspect-square bg-gray-100 rounded-2xl overflow-hidden shadow-inner flex items-center justify-center border-2 border-dashed border-gray-300">
          {generatedImage ? (
            <div className="relative w-full h-full group">
              <img
                src={generatedImage}
                alt="Generated Sneaker"
                className="w-full h-full object-contain p-4"
              />
               <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                  <a 
                    href={generatedImage} 
                    download={`kenya-amazon-custom-${Date.now()}.png`}
                    className="bg-white text-black p-3 rounded-full hover:scale-110 transition-transform"
                    title="Download"
                  >
                    <Download className="w-6 h-6" />
                  </a>
                  <button
                    onClick={handleAddToCatalog}
                    className="bg-indigo-600 text-white px-6 py-3 rounded-full font-bold hover:scale-105 transition-transform"
                  >
                    Add to Shop
                  </button>
               </div>
            </div>
          ) : (
            <div className="text-center p-8">
              <div className="w-24 h-24 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-400">
                <Sparkles className="w-10 h-10" />
              </div>
              <p className="text-gray-500 font-medium">Your creation will appear here</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};